name: 'Netlify Previews'

on:
  push:
    branches-ignore: 
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: h1oRy_nsUDk9czP_eQICH5GejCfv8YD4o92odSRAlIA
      NETLIFY_SITE_ID: f3ae3f59-26e2-47e6-8a57-21385d42b728

    steps:
      - uses: actions/checkout@v1

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_alias: ${{ env.BRANCH_NAME }}
      
      # Creates a status check with link to preview
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://${{ env.BRANCH_NAME }}--my-site.netlify.app